import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
import os
from dotenv import load_dotenv

load_dotenv()

def send_alert_email(image_path: str, recipient_email: str, subject: str = "URGENT: Poacher Detected - EcoEye AI", body: str = None, location_link: str = None):
    # Try both naming conventions
    sender_email = os.getenv("EMAIL_SENDER") or os.getenv("MAIL_USERNAME")
    sender_password = os.getenv("EMAIL_PASSWORD") or os.getenv("MAIL_PASSWORD")
    if sender_password:
        sender_password = sender_password.replace(" ", "")

    print(f"DEBUG: Sender: {sender_email[:3]}***@{sender_email.split('@')[-1]}")
    print(f"DEBUG: Recipient: {recipient_email}")
    
    if not sender_email or not sender_password:
        print("Error: Email credentials not found in environment variables.")
        return False

    print(f"DEBUG: Connecting to SMTP server...")
    
    try:
        msg = MIMEMultipart()
        msg['Subject'] = subject
        msg['From'] = sender_email
        msg['To'] = recipient_email

        # HTML Body Construction
        html_body = f"""
        <html>
          <body>
            <h2>{subject}</h2>
            <p>{body.replace(chr(10), '<br>') if body else '⚠️ Threat detected by EcoEye AI.'}</p>
        """

        if location_link:
            html_body += f"""
            <p>
              <b>📍 Incident Location:</b> <a href="{location_link}">View on Google Maps</a>
            </p>
            """

        html_body += """
            <p>Please review the attached evidence.</p>
            <br>
            <small>Generated by EcoEye AI Surveillance System</small>
          </body>
        </html>
        """

        # Attach HTML part
        msg.attach(MIMEText(html_body, 'html'))

        # Image Attachment
        if image_path and os.path.exists(image_path):
            try:
                with open(image_path, 'rb') as f:
                    img_data = f.read()
                    import imghdr
                    subtype = imghdr.what(None, img_data) or 'jpeg'
                    image = MIMEImage(img_data, name=os.path.basename(image_path), _subtype=subtype)
                    msg.attach(image)
                    print(f"DEBUG: Attached image {os.path.basename(image_path)}", flush=True)
            except Exception as img_err:
                 print(f"ERROR: Failed to attach image: {img_err}", flush=True)
        else:
            print(f"Warning: Image file not found at {image_path}", flush=True)

        # Connect to Gmail SMTP (standard port 587)
        print("DEBUG: Connecting to smtp.gmail.com:587...", flush=True)
        
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            # server.set_debuglevel(1) # Disable verbose logging to reduce noise
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
            
        print("DEBUG: Email sent successfully!", flush=True)
        return True

    except smtplib.SMTPAuthenticationError as e:
        msg = f"ERROR: SMTP Authentication Failed! Check your EMAIL_SENDER/PASSWORD in .env. {e}"
        print(msg, flush=True)
        with open("mail_debug.log", "a") as f: f.write(f"{datetime.now()} - {msg}\n")
        return False
    except Exception as e:
        msg = f"ERROR: SMTP Connection Failed: {e}"
        print(msg, flush=True)
        with open("mail_debug.log", "a") as f: f.write(f"{datetime.now()} - {msg}\n")
        return False

def send_password_reset_email(recipient_email: str, reset_link: str):
    subject = "Reset Your Password - EcoEye AI"
    body = f"""Hello,

You have requested to reset your password for EcoEye AI.
Please click the link below to verify your identity and set a new password:

{reset_link}

If you did not request this, please ignore this email.
This link will expire in 30 minutes.

Regards,
EcoEye AI Security Team
"""
    return send_alert_email("no_image_needed", recipient_email, subject, body, location_link=None)
